import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Header/Navbar";
import Footer from "./components/Footer";
import UserContextProvider from "./context/User/UserContextProvider";
import CartContextProvider from "./context/Cart/CartContextProvider";
import UpdateUserDetails from "./components/UpdateUserDetails";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vibe Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen w-screen overflow-x-hidden scrollbar-hidden flex flex-col`}>
        <CartContextProvider>
          <UserContextProvider>
            <UpdateUserDetails />
            <Navbar />
            {children}
            <Footer />
          </UserContextProvider>
        </CartContextProvider>
      </body>
    </html>
  );
}
